name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build

      - run: |
          cd dist
          ls -al
          VERSION=${GITHUB_REF/refs\/tags\//}
          TAG='latest'
          if [[ $VERSION =~ 'alpha' || $VERSION =~ 'beta' || $VERSION =~ 'rc' ]]; then
            TAG='next'
          fi
          npm publish --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # @see https://github.com/actions/create-release/issues/38#issuecomment-715327220
      # @see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
      - name: Prepare the changelog from the tag message
        id: prepare_changelog
        run: |
          # Parse version
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "Setting release version to $VERSION"
          echo "release_version=$VERSION" >> $GITHUB_ENV

          echo "$GITHUB_REF"
          echo "$GITHUB_REF_NAME"

          PRERELEASE=false
          # Check release type
          if [[ $VERSION =~ 'alpha' || $VERSION =~ 'beta' || $VERSION =~ 'rc' ]]; then
            echo "This is a prerelease."
            PRERELEASE=true
          fi
          echo "is_prerelease=$PRERELEASE" >> $GITHUB_ENV

          git show $GITHUB_REF

          CHANGELOG=$(git show $GITHUB_REF | tail -n+7)

          # Set markdown titles
          CHANGELOG=${CHANGELOG/Added/## Added}
          CHANGELOG=${CHANGELOG/Fixed/## Fixed}
          CHANGELOG=${CHANGELOG/Changed/## Changed}
          CHANGELOG=${CHANGELOG/Removed/## Removed}
          CHANGELOG=${CHANGELOG/Deprecated/## Deprecated}
          CHANGELOG=${CHANGELOG/Security/## Security}

          # Remove PGP signature
          CHANGELOG="${CHANGELOG%-----BEGIN*}"

          echo "$CHANGELOG"

          # Change linebreaks and other special characters
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

          echo $CHANGELOG

          echo 'changelog<<EOF' >> $GITHUB_ENV
          echo $CHANGELOG >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      # @see https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ env.release_version }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: ${{ env.is_prerelease }}
