name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build

      - run: |
          cd dist
          ls -al
          VERSION=${GITHUB_REF/refs\/tags\//}
          TAG='latest'
          if [[ $VERSION =~ 'alpha' || $VERSION =~ 'beta' || $VERSION =~ 'rc' ]]; then
            TAG='next'
          fi
          npm publish --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # @see https://github.com/actions/create-release/issues/38#issuecomment-715327220
      # @see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
      - name: Prepare the changelog from the tag message
        id: prepare_changelog
        run: |
          PRERELEASE=false
          # Check release type
          if [[ $GITHUB_REF_NAME =~ 'alpha' || $GITHUB_REF_NAME =~ 'beta' || $GITHUB_REF_NAME =~ 'rc' ]]; then
            echo "This is a prerelease."
            PRERELEASE=true
          fi
          echo "is_prerelease=$PRERELEASE" >> $GITHUB_ENV

      # @see https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref_name }}
          body: Please refer to [CHANGELOG.md](https://github.com/studiometa/vue-mapbox-gl/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          draft: false
          prerelease: ${{ env.is_prerelease }}

